### ISSUE TITLE
email_config error

### ISSUE THREAD

**Issue by tswagger** [emreakay/CodeIgniter-Aauth#158] opened 2016-07-15 01:46 UTC
Getting a error when using an email config file.  When config file is named email.php it does NOT need to be initialized in CI3.
Severity: Notice
Message:  Undefined index: email_config
Filename: libraries/Aauth.php
Line Number: 912

Suggested fix:
change line 912 from
`if(is_array($this->config_vars['email_config'])){`
to
`if(isset($this->config_vars['email_config']) && is_array($this->config_vars['email_config'])){`

I am not sure if there are other ramifications to this suggested fix, but it eliminated the error I was getting.

**Comment by tswagger** [comment] 2016-07-15 20:15
also on line 478

**Comment by REJack** [comment] 2016-07-16 13:27
Hi Tim,

The error comes because the `email_config` isn't in the aauth's config file.

I'm doesn't know the trick with `email.php` :dizzy_face: , i fix it now and create a release for it.

**Comment by REJack** [comment] 2016-07-16 13:36
Fix is released :smile:, now the `email.php` should work.

**Comment by REJack** [comment] 2016-07-20 16:11
I'll close this issue, if the problem is still there reopen the issue :smiley:.

**Closed by REJack** 2016-07-20 16:11 UTC
