### ISSUE TITLE
Why the method system_var not exist?

### ISSUE THREAD

**Issue by alederzz** [emreakay/CodeIgniter-Aauth#159] opened 2016-07-16 20:10 UTC
Hello , I downloaded the library , but I have seen do not have the System_var table or their methods .

What is the cause of that ?

**Comment by REJack** [comment] 2016-07-16 21:01
duplicate of #155

**Closed by REJack** 2016-07-16 21:01 UTC

**Comment by alederzz** [comment] 2016-07-16 21:10
Oh, i am sorry @REJack
