### ISSUE TITLE
Aauth doesn't work

### ISSUE THREAD

**Issue by Firefly16** [emreakay/CodeIgniter-Aauth#118] opened 2016-04-26 09:32 UTC
Hi, i'm new with codeigniter, your plugin seems interresting but i dont know if i instal not well or there is a problem. I use codeigniter 3.0.6 and xampp.

I put the application/libraries/Aauth.php in libraries, application/config/aauth.php in config and application/controller/example.php in controller.

Next I import the sql file in phpmyadmin (with aauth for DB name). After that i put the helpers in helper folder even if it's not mentionned. Same for languages.

And then "You must set up database connections from application/config/database.php" I puted 'database' => 'aauth'. "You can also make some changes on application/config/aauth.php". I do nothing.

I create a controller and write the "$this->load->library("Aauth");" in __construct, and do the tutorial.

Problems are:

Fatal error: Call to undefined method Aauth::deny()
If i dont use the deny function, there is no error but when i look in the DB i only have legolas and no frodo or gandalf. But all perms and groups are there.
If i give "immortality to hobbits", it still say that hobbits have not "immortality".

2 days looking, help plz :'(

**Comment by Firefly16** [comment] 2016-04-26 13:17
For the problem where people dont go on DB, it seems when we have blank/underscore, this doesn't work :/

**Comment by REJack** [comment] 2016-05-01 13:06
1. please give me your written code to reproduce your problem
2. the master has some new enhancements (PHP7 fix & more) since 2.4.6

**Comment by REJack** [comment] 2016-05-01 13:14
the function `deny` is moved to `deny_user` & `deny_group`
i fix it in the `Quick Start`-Section

**Comment by Firefly16** [comment] 2016-05-02 07:32
Hello, for the deny function i saw it, i looked in the library to see if the function was there :)

So for deny it's ok. For perms i saw that the order of parameters is différent in your tutorial and the library so it work too now.

The only problem left is the space who doesn't work, here is my code:

```
public function __construct() {
        parent::__construct();
        $this->load->library("Aauth"); 
        $this->load->library('form_validation');
        $this->form_validation->set_error_delimiters('<div class="error">', '</div>');
        $this->load->database();
}


public function create_user(){

        $this->form_validation->set_rules('nickname', 'Nickname', 'trim|required|min_length[3]|max_length[60]|alpha_numeric');
        $this->form_validation->set_rules('password', 'Password', 'trim|required|min_length[3]|max_length[60]|alpha_numeric');
        $this->form_validation->set_rules('email', 'E-mail', 'trim|required|valid_email');

        if($this->form_validation->run()){
            $data['nickname'] = $this->input->post('nickname');
            $data['password'] = $this->input->post('password');
            $data['email'] = $this->input->post('email');
            $this->aauth->create_user($data['email'], $data['password'], $data['nickname']);

            $this->load->view('confirmation_view',$data);
        }else{
            $data['signup'] = 1;
            $this->load->view('homepage_view',$data);
            
        }
```

Thank you for taking time for me :)

**Comment by REJack** [comment] 2016-05-02 08:06
a underscore in the users name?

**Comment by Firefly16** [comment] 2016-05-02 08:09
Space and underscore both don't work :/

**Comment by REJack** [comment] 2016-05-02 08:10
you need to add both in the `valid_chars`-array in your aauth config [Line 97](https://github.com/emreakay/CodeIgniter-Aauth/blob/master/application/config/aauth.php#L97)

**Comment by Firefly16** [comment] 2016-05-02 08:19
Mmh, i'm not a pro in array, this doesn't work: 'valid_chars'  => array(space  => ' ', underscore => '_'). And i'm pretty sure that's an horrible code ^^'

**Comment by REJack** [comment] 2016-05-02 08:26
nope a simple array without specific keys (Indexed Arrays)

`'valid_chars' => array(' ', '_')`

this should work :) (its not a horrible code but a Associative Array)

**Comment by Firefly16** [comment] 2016-05-02 08:36
Thx you, it works !

A difficult start for me but finally an awesome library who easy the task !

**Comment by REJack** [comment] 2016-05-02 08:38
no problem :+1: 

please close this issue :smile: 
(if you have an other problem you can open any time a new one)

**Closed** 2016-05-02 08:40 UTC
